version: "3"

services:
  db:
    image: mysql:8
    env_file: .env
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  drupal:
    build: .
    depends_on:
      - db
    volumes:
      - ./drupal-data/modules:/var/www/html/modules
      - ./drupal-data/themes:/var/www/html/themes
      - ./drupal-data/files:/opt/drupal/web/sites/default/files
      - ./drupal-data/libraries:/opt/drupal/web/sites/default/libraries
    env_file: .env
    ports:
      - "${EXPOSED_PORT}:80"

  pma:
    image: phpmyadmin:latest
    ports:
      - "8800:80"
    env_file: .env
